on:
  push:
    branches: [master]
name: Release Subctl Bleeding Edge
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Generate the Artifacts
        run: |
          make build-cross
          echo "::set-env name=BINARIES::$(find bin/ -type f -name '*.tar.xz' -printf '%p ')"

      - name: Bump the devel tag
        uses: richardsimko/update-tag@v1.0.3
        with:
          tag_name: devel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update the Release
        uses: johnwbyrd/update-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: Bleeding edge
          message: |
            This is the latest binary, built straight from the master branch.
            As such, it might break or not work as you expect.
            If you want a stable binary, check out [the latest stable](https://github.com/submariner-io/submariner-operator/releases/latest) release.
          tag: devel
          files: ${{ env.BINARIES }}
